# Generated by Django 5.0.7 on 2024-07-23 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('set_duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='PublicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.folder')),
                ('text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.textdata')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=6, unique=True)),
                ('files', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.folder')),
                ('text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.textdata')),
            ],
        ),
    ]
