# Generated by Django 5.0.7 on 2024-07-23 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_textdata_publicdata_privatedata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivateData',
            new_name='PrivateText',
        ),
        migrations.CreateModel(
            name='PrivateFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=6, unique=True)),
                ('files', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.folder')),
            ],
        ),
        migrations.CreateModel(
            name='PublicFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.folder')),
            ],
        ),
        migrations.CreateModel(
            name='PublicText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.textdata')),
            ],
        ),
        migrations.DeleteModel(
            name='PublicData',
        ),
    ]
