# Generated by Django 5.0.7 on 2024-07-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_privatedata_privatetext_privatefiles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatetext',
            name='files',
        ),
    ]
