# Generated by Django 5.0.7 on 2024-07-23 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_publicfiles_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicfiles',
            name='files',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.folder'),
        ),
    ]
