# Generated by Django 5.0.6 on 2024-08-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_publicfiles_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
